blog/urls.py
from django.urls import path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blog, name='all_blog'),
    path('<int:blog_id>/', views.detail, name='detail')
]

personal_protfolio/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', views.home, name='home'),
]
# added media root for accessing media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import admin
from django.db import models


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    desc = models.TextField()
    publish_date = models.DateField()
    blog_image = models.ImageField(upload_to='blog/image')

    def __str__(self):
        return self.title


class BlogAdmin(admin.ModelAdmin):
    search_fields = ('title', 'desc')

portfolio/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/image')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404

# Create your views here.
from blog.models import Blog


def all_blog(request):
    blog_count = Blog.objects.count()
    blog_list = Blog.objects.order_by('-publish_date')[:3]
    return render(request, 'all_blogs.html', {'blog_list': blog_list,
                                              'blog_count': blog_count})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    return render(request, 'blog_detail.html', {'blog': blog})

portfolio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render

# Create your views here.
from portfolio.models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

blog/templates/all_blogs.html
{% extends 'base.html' %}
{% block content %}
    <title>All Blog</title>
<h2>Mujahid has written {{ blog_count }} blog{{ blog_count|pluralize }}</h2>
<br>
    {% for blog in blog_list %}
        <a href="{% url 'blog:detail' blog.id %}"><h1>{{ blog.title }}</h1></a>
        <br>
        {{ blog.desc|striptags|truncatechars:100 }}
        <br>
        <br>
       Publish Date: {{ blog.publish_date|date:'M d Y' }}
    {% endfor %}

{% endblock %}

blog/templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}
    <title>Blog Detail</title>
        <img src="{{ blog.blog_image.url }}" width="300" height="300">
        <h1>{{ blog.title }}</h1>
            <h2> Publish Date: {{ blog.publish_date|date:'F jS Y' }}</h2>
    <p>{{ blog.desc|striptags }}</p>

{% endblock %}

portfolio/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "files/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "files/Logo.png" %}">

  <title>Mujahid Khan</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "files/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Mujahid Khan</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "files/resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/nick-walter/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/ZappyCode" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blog' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'files/profile_image.jpg' %}" class="img-fluid" height="300" width="300">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Mujahid Khan is Commander-in-Chief at Mk7Lab, Khulna, BD 😊</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2" width="300" height="300">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2" width="300" height="300">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}